### ISSUE TITLE
[NumberGuesser] %NAME

### ISSUE THREAD

**Issue by pavel-b-novikov** [lopus-mopus/Nsudotnet#6]
```Console.WriteLine(OATH[random.Next(0, OATH.Length)].Replace("%NAME", userName));```

Я даже картинку на стене в группу на эту тему постил. Правда с прошлого года. 
Это какой-то.. позор

**Comment by Data667** [comment]
Что за ад, все нормальные люди делают это через Marshall.
Прям реально неадекват
