### ISSUE TITLE
[NumberGuesser] int.Parse(Console.ReadLine());

### ISSUE THREAD

**Issue by pavel-b-novikov** [lopus-mopus/Nsudotnet#7]
Обыграйте без exception-а пожалуйста

**Comment by lopus-mopus** [comment]
хорошо, я постараюсь успеть исправить все косяки по этой лабе к вечеру среды

**Comment by pavel-b-novikov** [comment]
слушайте, если вы думаете, что я собираюсь проверять ваши задачи завтра в 6 утра, то вы ошибаетесь

**Comment by lopus-mopus** [comment]
я часа 3 назад, выложил новую версию, в которой сделал это без exception
